### ISSUE TITLE
Error running server in windows environment

### ISSUE THREAD

**Issue by ahmedshoaib** [s-xync/auction-away#24]
Starting the server in windows node environment gives an error with bcrypt_lib.node : 

$ npm start

> auction-away@1.0.0 start C:\Users\SECONDARY\Documents\auction-away
> node app.js

module.js:681
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: \\?\C:\Users\SECONDARY\Documents\auction-away\node_modules\bcrypt\lib\binding\bcrypt_lib.node is not a valid Win32 application.
\\?\C:\Users\SECONDARY\Documents\auction-away\node_modules\bcrypt\lib\binding\bcrypt_lib.node
    at Object.Module._extensions..node (module.js:681:18)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\SECONDARY\Documents\auction-away\node_modules\bcrypt\bcrypt.js:6:16)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\SECONDARY\Documents\auction-away\models\user.js:2:16)
    at Module._compile (module.js:652:30)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! auction-away@1.0.0 start: `node app.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the auction-away@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\SECONDARY\AppData\Roaming\npm-cache\_logs\2018-04-04T04_15_41_005Z-debug.log

**Comment by s-xync** [comment]
If you are using a windows environment, there are problems that users have been reporting about 'bcrypt' package not working. Instead of 'bcrypt' package, use 'bcryptjs'. Change 'bcrypt' to 'bcryptjs' in 'package.json' file then open the 'user.js' file and change 'var bcrypt = require('bcrypt');' to 'var bcrypt = require('bcryptjs');'. After that, run 'npm install' and then 'npm start'.
